# Generated by Django 3.0.7 on 2020-06-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
